name: environment
channels:
  - conda-forge
  - damianavila82
dependencies:
  - _ipyw_jlab_nb_ext_conf
  - _tflow_190_select
  - absl-py
  - alabaster
  - anaconda
  - anaconda-client
  - anaconda-navigator
  - anaconda-project
  - asn1crypto
  - astor
  - astroid
  - astropy
  - attrs
  - babel
  - backcall
  - backports
  - backports.weakref
  - backports.shutil_get_terminal_size
  - beautifulsoup4
  - bitarray
  - bkcharts
  - blas
  - blaze
  - bleach
  - blosc
  - bokeh
  - boto
  - bottleneck
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - clyent
  - colorama
  - conda
  - conda-build
  - conda-env
  - conda-verify
  - contextlib2
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - datashape
  - dbus
  - decorator
  - distributed
  - docutils
  - enum34
  - entrypoints
  - et_xmlfile
  - expat
  - fastcache
  - filelock
  - flask
  - funcsigs
  - flask-cors
  - futures
  - fontconfig
  - freetype
  - gast
  - get_terminal_size
  - gevent
  - glib
  - glob2
  - gmp
  - gmpy2
  - graphite2
  - greenlet
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - harfbuzz
  - hdf5
  - heapdict
  - html5lib
  - icu
  - idna
  - imageio
  - imagesize
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jbig
  - jdcal
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterlab
  - jupyterlab_launcher
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - kiwisolver
  - lazy-object-proxy
  - lightgbm
  - libcurl
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libprotobuf
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libtool
  - libxcb
  - libxml2
  - libxslt
  - llvmlite
  - locket
  - lxml
  - lzo
  - markdown
  - markupsafe
  - matplotlib
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mock
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multipledispatch
  - navigator-updater
  - nbconvert
  - nbformat
  - ncurses
  - networkx
  - ninja
  - nltk
  - nose
  - notebook
  - numba
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - odo
  - olefile
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parso
  - partd
  - patchelf
  - path.py
  - pathlib2
  - patsy
  - pbr
  - pcre
  - pep8
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkginfo
  - pluggy
  - ply
  - prompt_toolkit
  - protobuf
  - psutil
  - ptyprocess
  - py
  - pycodestyle
  - pycosat
  - pycparser
  - pycrypto
  - pycurl
  - pyecharts
  - pyflakes
  - pygments
  - pylint
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - pytables
  - pytest
  - pytest-arraydiff
  - pytest-astropy
  - pytest-doctestplus
  - pytest-openfiles
  - pytest-remotedata
  - python
  - python-dateutil
  - pytorch
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtawesome
  - qtconsole
  - qtpy
  - readline
  - requests
  - rope
  - ruamel_yaml
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - simplejson
  - simplegeneric
  - singledispatch
  - sip
  - six
  - snappy
  - snowballstemmer
  - sortedcollections
  - sortedcontainers
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-websupport
  - spyder
  - sqlalchemy
  - sqlite
  - statsmodels
  - sympy
  - tblib
  - tensorboard
  - tensorflow
  - tensorflow-base
  - termcolor
  - terminado
  - testpath
  - tk
  - toolz
  - torchvision
  - tornado
  - traitlets
  - typing
  - unicodecsv
  - unixodbc
  - urllib3
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - wrapt
  - xlrd
  - xlsxwriter
  - xgboost
  - jieba
  - kreas
  - xlwt
  - xz
  - yaml
  - zeromq
  - zict
  - zlib
  - rise
  - ipyvolume
  - PIL
  - boto
